"""`sg init` (set a repo up in one command) and `sg doctor` (why can't sg run here?)."""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from typing import Any

from sg.core import git, registry
from sg.core.discover import discover_services
from sg.core.policy import POLICY_FILE, TABLE_CLASSES
from sg.core.sql import parse, touches

MARKETPLACE = {"schema-guard": {"source": {"source": "github", "repo": "vialyx/schema-guard"}}}
PLUGIN = "schema-guard@schema-guard"
WORKFLOW = """\
# schema-guard gate: checks every PR that changes migrations. Make it a required check.
# NEEDS-HUMAN passes once someone with write access adds the `schema-guard:approved` label;
# REFUSED never passes.
name: schema-guard
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  schema-guard:
    uses: vialyx/schema-guard/.github/workflows/gate.yml@main
    # with:
    #   setup: pip install -r services/api/requirements.txt   # deps your services' tests need
"""
# Name hints for a first guess at table classes; the engineer confirms them.
_CLASS_HINTS = [
    ("ledger", re.compile(r"ledger|journal|posting|transaction|payment|invoice|balance")),
    ("audit", re.compile(r"audit|history|_log$|event")),
    ("scratch", re.compile(r"staging|tmp|temp|scratch|import")),
]


def _guess_class(table: str) -> str:
    for cls, pat in _CLASS_HINTS:
        if pat.search(table.lower()):
            return cls
    return "core"


def _tables(service_root: Path, adapter_name: str) -> list[str]:
    """Tables the existing migrations create, from their offline SQL (best effort)."""
    try:
        adapter = registry.adapters()[adapter_name](service_root)
        found: list[str] = []
        for m in adapter.list_migrations():
            for t in touches(parse(adapter.render_sql(m.id), "postgres")):
                if t.op == "create_table" and t.table not in found:
                    found.append(t.table.split(".")[-1].strip('"'))
        return found
    except Exception:
        return []


def _base_ref(repo: Path) -> str:
    head = git._git(repo, "symbolic-ref", "--quiet", "refs/remotes/origin/HEAD").stdout.strip()
    if head:
        return head.rsplit("/", 1)[-1]
    for name in ("main", "master"):
        if git.ref_exists(repo, name) or git.ref_exists(repo, f"origin/{name}"):
            return name
    return "main"


def render_policy(repo: Path) -> tuple[str, list[str]]:
    """(schema-guard.yaml text, TODOs for the engineer)."""
    services = discover_services(repo)
    if not services:
        raise FileNotFoundError(
            f"no migrations found under {repo} (looked for alembic.ini and V<n>__*.sql files). "
            "Write schema-guard.yaml by hand; see examples/acme-mini-org/schema-guard.yaml"
        )
    todos: list[str] = []
    lines = [
        "# schema-guard policy. Generated by `sg init`; review every TODO, then commit.",
        "# Reference: https://github.com/vialyx/schema-guard/blob/main/examples/acme-mini-org/schema-guard.yaml",
        "version: 1",
        "dialect: postgres",
        f"base_ref: {_base_ref(repo)}   # a migration on this branch counts as shipped",
        "",
        "services:",
    ]
    tables: dict[str, str] = {}
    for svc in services:
        root = repo / svc.path
        lines.append(f"  - path: {svc.path}")
        lines.append(f"    adapter: {svc.adapter}")
        if (root / "seed.sql").exists():
            lines.append("    seed: seed.sql")
        else:
            lines.append("    # seed: seed.sql   # TODO: synthetic data enables the business-invariant checks")
            todos.append(f"{svc.path}: add seed.sql so invariants can run")
        if (root / "tests").is_dir() or (root / "pytest.ini").exists():
            lines.append('    tests: "python -m pytest -q"')
        else:
            lines.append('    # tests: "python -m pytest -q"   # TODO: the command that runs this service\'s tests')
            todos.append(f"{svc.path}: set `tests:`")
        for t in _tables(root, svc.adapter):
            tables.setdefault(t, _guess_class(t))
    lines += ["", f"# Table classes: {' | '.join(TABLE_CLASSES)}. est_rows drives lock-risk judgments.",
              "# TODO: confirm each class (guessed from the name) and add est_rows from production.", "tables:"]
    lines += [f"  {t}: {{class: {c}}}" for t, c in sorted(tables.items())] or ["  {}"]
    if tables:
        todos.append("confirm table classes and add est_rows")
    lines += ["", "# Queries whose result must not change across a migration (run on seed data).",
              "invariants: []", ""]
    return "\n".join(lines), todos


def cmd_init(args) -> int:
    repo = git.git_root(Path(args.path)) or Path(args.path).resolve()
    written: list[str] = []
    skipped: list[str] = []

    def write(rel: str, content: str) -> None:
        f = repo / rel
        if f.exists() and not args.force:
            skipped.append(f"{rel} (exists; --force to overwrite)")
            return
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(content)
        written.append(rel)

    policy, todos = render_policy(repo)
    write(POLICY_FILE, policy)
    write(".github/workflows/schema-guard.yml", WORKFLOW)

    gi = repo / ".gitignore"
    existing = gi.read_text() if gi.exists() else ""
    if ".schema-guard/" not in existing.split():
        gi.write_text(existing + ("" if existing.endswith("\n") or not existing else "\n") + ".schema-guard/\n")
        written.append(".gitignore (+ .schema-guard/)")

    settings = repo / ".claude" / "settings.json"
    data: dict[str, Any] = json.loads(settings.read_text()) if settings.exists() else {}
    if data.get("enabledPlugins", {}).get(PLUGIN) is None:
        data.setdefault("extraKnownMarketplaces", {}).update(MARKETPLACE)
        data.setdefault("enabledPlugins", {})[PLUGIN] = True
        settings.parent.mkdir(exist_ok=True)
        settings.write_text(json.dumps(data, indent=2) + "\n")
        written.append(".claude/settings.json (plugin enabled for everyone)")

    print(json.dumps({"written": written, "skipped": skipped, "todo": todos,
                      "next": ["review the TODOs in schema-guard.yaml",
                               "add CODEOWNERS entries for migration dirs and schema-guard.yaml",
                               "run `sg doctor`, then commit"]}, indent=2))
    return 0


def cmd_doctor(args) -> int:
    from sg.core.context import load_policy
    from sg.core.policy import find_repo_root

    rows: list[tuple[bool | None, str, str]] = []  # (ok / None = advisory, what, detail or fix)
    path = Path(args.path)
    root = git.git_root(path)
    rows.append((root is not None, "git repository", str(root) if root else "run inside a git checkout"))
    repo = find_repo_root(path)
    has_policy = (repo / POLICY_FILE).exists()
    rows.append((has_policy, POLICY_FILE, str(repo / POLICY_FILE) if has_policy
                 else "not found: zero-config mode; run `sg init` to write one"))
    rows.append((bool(shutil.which("uv")), "uv", "needed by the plugin's `sg` launcher: https://docs.astral.sh/uv/"))
    squawk = shutil.which("squawk") or shutil.which("npx")
    rows.append((bool(squawk), "squawk (lock linter)", squawk or "install Node (npx) or squawk; without it GO is impossible"))

    try:
        policy, base, _ = load_policy(repo, None)
        found = git.ref_exists(repo, base)
        rows.append((found, f"base ref `{base}`", "found" if found else
                     f"missing: git fetch origin {base.removeprefix('origin/')} (CI: fetch-depth: 0)"))
        for svc in policy.services:
            try:
                from sg.core.context import build_context

                ctx = build_context(repo / svc.path)
                rows.append((True, f"service `{svc.path}`",
                             f"{ctx.adapter.name}, {len(ctx.migrations)} migrations, python: {' '.join(ctx.adapter.python)}"))
                rows.append((True if svc.tests else None, f"  tests for `{svc.path}`",
                             svc.tests or "no `tests:` command; the tests check will only warn"))
            except Exception as exc:
                rows.append((False, f"service `{svc.path}`", str(exc)))
        dialect_cls = registry.dialects()[policy.dialect]
        ok, how = dialect_cls.available()
        if ok:
            try:
                server = dialect_cls().ephemeral_server()
                server.create_database("sg_doctor")
                server.stop()
                rows.append((True, "throwaway database", how))
            except Exception as exc:
                hint = (" (initdb refuses to run as root: set SG_DATABASE_URL to a disposable server)"
                        if "root" in str(exc) else "")
                rows.append((False, "throwaway database", f"{type(exc).__name__}: {str(exc)[:160]}{hint}"))
        else:
            rows.append((False, "throwaway database", how))
    except Exception as exc:
        rows.append((False, "policy", str(exc)))

    for ok, what, detail in rows:
        print(f"{'✅' if ok else '⚠️' if ok is None else '❌'} {what}: {detail}")
    bad = sum(ok is False for ok, _, _ in rows)
    print("\nall good" if not bad else f"\n{bad} problem(s); checks that need them will be skipped (verdict ≤ NEEDS-HUMAN)")
    return 0 if not bad else 3
